/************************************************************************************/
/* 	      Digital Epidemiologist Pre-interview Task - Parse Data Questions          */
/************************************************************************************/

/*Kristiana Dhillon*/
/*February 20, 2022*/

/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Sunday, February 20, 2022 at 11:17:07 AM
   By task:     Import Data Wizard
   
   Source file: C:\Users\kdhillo2\Desktop\data.csv
   Server:      Local File System
   
   Output data: SASUSER.OXFORDDATA
   Server:      Local
   -------------------------------------------------------------------- */

DATA SASUSER.OXFORDDATA;
    LENGTH
        sample_name      $ 9
        result           $ 7
        'confindr.contam_status.metric_va'n $ 5
        'confindr.contam_status.check_res'n $ 7
        'confindr.percentage_contaminatio'n   8
        'confindr.percentage_contami_0001'n $ 7
        'quast.# contigs (>= 1000 bp).met'n   8
        'quast.# contigs (>= 1000 bp).che'n $ 7
        'quast.N50.metric_value'n   8
        'quast.N50.check_result'n $ 7
        'quast.Total length (>= 1000 bp).'n   8
        'quast.Total length (>= 1000_0001'n $ 7 ;
    LABEL
        'confindr.contam_status.metric_va'n = "confindr.contam_status.metric_value"
        'confindr.contam_status.check_res'n = "confindr.contam_status.check_result"
        'confindr.percentage_contaminatio'n = "confindr.percentage_contamination.metric_value"
        'confindr.percentage_contami_0001'n = "confindr.percentage_contamination.check_result"
        'quast.# contigs (>= 1000 bp).met'n = "quast.# contigs (>= 1000 bp).metric_value"
        'quast.# contigs (>= 1000 bp).che'n = "quast.# contigs (>= 1000 bp).check_result"
        'quast.Total length (>= 1000 bp).'n = "quast.Total length (>= 1000 bp).metric_value"
        'quast.Total length (>= 1000_0001'n = "quast.Total length (>= 1000 bp).check_result" ;
    FORMAT
        sample_name      $CHAR9.
        result           $CHAR7.
        'confindr.contam_status.metric_va'n $CHAR5.
        'confindr.contam_status.check_res'n $CHAR7.
        'confindr.percentage_contaminatio'n BEST5.
        'confindr.percentage_contami_0001'n $CHAR7.
        'quast.# contigs (>= 1000 bp).met'n BEST4.
        'quast.# contigs (>= 1000 bp).che'n $CHAR7.
        'quast.N50.metric_value'n BEST7.
        'quast.N50.check_result'n $CHAR7.
        'quast.Total length (>= 1000 bp).'n BEST8.
        'quast.Total length (>= 1000_0001'n $CHAR7. ;
    INFORMAT
        sample_name      $CHAR9.
        result           $CHAR7.
        'confindr.contam_status.metric_va'n $CHAR5.
        'confindr.contam_status.check_res'n $CHAR7.
        'confindr.percentage_contaminatio'n BEST5.
        'confindr.percentage_contami_0001'n $CHAR7.
        'quast.# contigs (>= 1000 bp).met'n BEST4.
        'quast.# contigs (>= 1000 bp).che'n $CHAR7.
        'quast.N50.metric_value'n BEST7.
        'quast.N50.check_result'n $CHAR7.
        'quast.Total length (>= 1000 bp).'n BEST8.
        'quast.Total length (>= 1000_0001'n $CHAR7. ;
    INFILE 'C:\Users\kdhillo2\AppData\Roaming\SAS\EnterpriseGuide\EGTEMP\SEG-8560-6b27fe3f\contents\data-71242fc2f4a54e0a9698d263223e41c9.txt'
        LRECL=88
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='7F'x
        MISSOVER
        DSD ;
    INPUT
        sample_name      : $CHAR9.
        result           : $CHAR7.
        'confindr.contam_status.metric_va'n : $CHAR5.
        'confindr.contam_status.check_res'n : $CHAR7.
        'confindr.percentage_contaminatio'n : ?? COMMA5.
        'confindr.percentage_contami_0001'n : $CHAR7.
        'quast.# contigs (>= 1000 bp).met'n : ?? BEST4.
        'quast.# contigs (>= 1000 bp).che'n : $CHAR7.
        'quast.N50.metric_value'n : ?? BEST7.
        'quast.N50.check_result'n : $CHAR7.
        'quast.Total length (>= 1000 bp).'n : ?? BEST8.
        'quast.Total length (>= 1000_0001'n : $CHAR7. ;
RUN;

/*Question 1

How many samples are there that have failed the contamination check (confindr.contam_status.check_result) 
and have contamination (confindr.percentage_contamination.metric_value) of over 5.0 (%)?*/
proc freq data=SASUSER.OXFORDDATA;
tables 'confindr.contam_status.check_res'n;
where 'confindr.percentage_contaminatio'n>5;
run;
/* There were 57 samples that failed the contamination check and had contamination of over 5.0%*/

/* Question 2 

How many samples are there that have less than or equal to 50 contigs and a N50 value of greater than 
or equal to 750,000?*/ 
proc freq data=SASUSER.OXFORDDATA;
tables sample_name;
where 'quast.# contigs (>= 1000 bp).met'n<=50 and 'quast.N50.metric_value'n>=750000;
run;
/* There were 49 samples that have less than or equal to 50 contigs and a N50 value of greater than 
or equal to 750,000*/

/* Question 3
Select all numeric columns and rename them to remove the . quast prefix and . metric_ value suffix, 
and rename confindr .percentage_contamination to contamination_percent*/
data SASUSER.OXFORDDATARENAMED;
set SASUSER.OXFORDDATA (rename=('confindr.percentage_contaminatio'n='contamination_percent'n 'quast.# contigs (>= 1000 bp).met'n='# contigs (>= 1000 bp)'n 'quast.N50.metric_value'n='N50'n 'quast.Total length (>= 1000 bp).'n='Total length (>= 1000 bp)'n)); 
run;
proc contents;
run;
/* Question 4

Make a box plot of Total length (>= 1000 bp)*/
proc sgplot data=SASUSER.OXFORDDATARENAMED;
vbox 'Total length (>= 1000 bp)'n;
yaxis label='Total length (>=1000 bp)';
run;
/* I changed the y axis label because it used the original label rather than the renamed variable */

/* Question 5 

Pivot the data so that it is 'tidy' with one observation per row and have final column headings of 
sam­ple_name, metric, value */

data SASUSER.OXFORDDATATIDY;
set SASUSER.OXFORDDATARENAMED(drop='result'n 'confindr.contam_status.check_res'n 'confindr.percentage_contami_0001'n 'quast.# contigs (>= 1000 bp).che'n 'quast.N50.check_result'n 'quast.Total length (>= 1000_0001'n); 
run;
proc sort data=SASUSER.OXFORDDATATIDY out=SASUSER.OXFORDDATATIDY2;
by 'sample_name'n;
run; 
proc transpose data=SASUSER.OXFORDDATATIDY2 
out=SASUSER.OXFORDDATATIDY3 (rename=(Col1=value)) name=metric label=original_label;
by 'sample_name'n;
var 'confindr.contam_status.metric_va'n 'contamination_percent'n '# contigs (>= 1000 bp)'n 'n50'n 'Total length (>= 1000 bp)'n;
run; 
data SASUSER.OXFORDDATATIDY4;
set SASUSER.OXFORDDATATIDY3(drop=original_label);
run;
/* See parts 1 and 2 for Question 5 in ppt. document*/

/* Question 6

Make a violin plot for each of the numeric variables in a single plot. Bonus: include jittered data points */
ods select none;
proc kde data=SASUSER.OXFORDDATATIDY2;
univar 'Total length (>= 1000 bp)'n (gridl=1000 gridu=15000000) /
NGRID=100 unistats percentiles plots=none
out=sasuser.lengthDensity (rename=(value='Total length (>= 1000 bp)'n) drop=var);
run;
ods select all;
data sasuser.lengthdensityplot;
set sasuser.lengthDensity;
mirror=-1*density;
zero=0;
run;
proc sgplot data=sasuser.lengthdensityplot;
band x='Total length (>= 1000 bp)'n upper=density lower=mirror /
fill outline;
xaxis label='Total length (>= 1000 bp) of Samples';
yaxis display=none;
run;
/* I only did one violin plot because I ran out of time - view in ppt. document*/

 